In [2]:
import numpy as np


In [3]:
# STARTING W
W=np.zeros(shape=(2,2))
W[0][0]=1
W[1][1]=1


beta = 0.1

print(W)

[[1. 0.]
 [0. 1.]]


In [3]:
# SHOULD BE A 0 (gets a tie, so its correct)
x=np.array([1,1,1,1,0,1,1,1,1])
y=np.matmul(W,x)
y

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1.])

In [4]:
# SHOULD BE A 0 (but gets more votes for 1s so its incorrect)
x=np.array([0,1,1,1,0,1,1,1,1])
y=np.matmul(W,x)
y

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1.])

In [5]:
# UPDATE INCORRECT GUESS UNTIL CORRECT

y[9:18]=0 # 0 out the "1s" area

x=x.reshape((9,1))
y=y.reshape((18,1))

while True:
    W = W + beta * np.multiply( np.matmul(y,x.T), W)
    s = np.matmul(W,x).reshape(2,9)
    
    if np.sum(s, axis=1)[0] > np.sum(s, axis=1)[1]:
        break
        
W


array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.14358881, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],


In [6]:
# CHECK THAT IT CORRECTLY SATISFIES ALL PREVIOUS INPUTS

def checkresult(W,x,out):
    s = np.matmul(W,x).reshape(2,9)
    if out==0:
        return np.sum(s, axis=1)[0] >= np.sum(s, axis=1)[1]
    else:
        return np.sum(s, axis=1)[1] > np.sum(s, axis=1)[0]
    

print(
    checkresult(W, np.array([1,1,1,1,0,1,1,1,1]), out=0),
    checkresult(W, np.array([0,1,1,1,0,1,1,1,1]), out=0)
)

True True


In [7]:
# SHOULD BE A 1 (but classifies as 0, so incorrect)
x=np.array([0,1,0,0,1,0,0,1,0])
y=np.matmul(W,x)
y

array([0.        , 2.14358881, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        ])

In [8]:
# UPDATE INCORRECT GUESS UNTIL CORRECT

y[0:9]=0 # 0 out the "0s" area

x=x.reshape((9,1))
y=y.reshape((18,1))

while True:
    W = W + beta * np.multiply( np.matmul(y,x.T), W)
    s = np.matmul(W,x).reshape(2,9)
    
    if np.sum(s, axis=1)[0] < np.sum(s, axis=1)[1]:
        break
        
W


array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.14358881, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],


In [9]:
# CHECK THAT IT CORRECTLY SATISFIES ALL PREVIOUS INPUTS

print(
    checkresult(W, np.array([1,1,1,1,0,1,1,1,1]), out=0),
    checkresult(W, np.array([0,1,1,1,0,1,1,1,1]), out=0),
    checkresult(W, np.array([0,1,0,0,1,0,0,1,0]), out=1)
)

False False True
